Adding composer install step outside sail

diff --git a/bin/check_dependencies b/bin/check_dependencies
--- a/bin/check_dependencies
+++ b/bin/check_dependencies
@@ -19,9 +19,21 @@ check_docker_status() {
     fi
 }
 
+# check composer installation
+check_composer_status() {
+    # check if composer is installed on local machine
+    if [ "x$(which composer)" == "x" ]; then
+        printf "\nComposer not found on local machine.\n"
+        printf "Composer is required to run the project\n"
+        printf "https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos\n"
+        exit 1
+    fi
+}
+
 # check dependencies
 check_dependencies() {
     check_docker_status
+    check_composer_status
 }
 
 check_dependencies
